import type { Metadata } from "next";
import "./globals.css";
import "./splash.scss";
import ParticlesComponent from "@/components/providers/ParticlesComponent";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen font-cabin scrollbar-non">
        {/* Splash screen */}
        <div className="splash">
          <div className="splash_logo">KARIM</div>
          <div className="splash_svg">
            <svg width="100%" height="100%">
              <rect width="100%" height="100%" />
            </svg>
          </div>
          <div className="splash_minimize">
            <svg width="100%" height="100%">
              <rect width="100%" height="100%" />
            </svg>
          </div>
        </div>

        <Header />
        <div id="particles" className="relative">
          <ParticlesComponent />
        </div>

        <div id="children" className="relative z-40">
          {children}
        </div>
      </body>
    </html>
  );
}
